### ISSUE TITLE
Owncloud 5.0 "Error while enabling app"

### ISSUE THREAD

**Issue by ghost** [pitbulk/apps#9]
i see this message when i try to enable the app, in the log there are this message:

"App can't be installed because the version in info.xml/version is not the same as the version reported from the app store"

its a problem with version 5?

**Comment by pitbulk** [comment]
user_saml works with owncloud 4.9.

Not tested with version 5.

Edit user_saml/appinfo/info.xml and change the require to 5 and check if works.

**Comment by ghost** [comment]
ok now it works perfectly with owncloud5!
